language: node_js
node_js: node
services: mongodb
env:
  matrix:
    secure: t4vnNexqVBKll3CecdNUv0slKlxSU0FnaRNInNZqK8pbzV8sjfsrwt/Iv275Xp1YmYdduq80/Zs4EcbqPpK/IHffkpakb9XheF21TAvoPPbnQm6tbXouEdCO/ADd/I6ItUlomLK48Fk3UW0gstWJQHkCGQd1n54F75SGQKxsoId048usrlFwac/hCbe2MUPeFu3cle8nw75Y1sGly6qO+3TIB4FLpBZIE/lJ5TSNWwn1bJw4ACI1J20YYCeqnXx8U6UoTgrvCNh2qYpjVptuu/4hiiXvQG1ckxAEhxV8iUc6T7I6EszTU4Is3sWOiP3znuKJMSTAT/1+jJxHhGUG5iPd/e+QTZQK5i87Aq0ycvPUCDtx+efpITXGv11MXLMvzQ4lUg7/HxESGucOdzYaodaUMilGxHomJk2CAw2pFI33tRnFHdeEyCj6fO8HNbnRRyG33l8+OvhkMR/x2OvzHLApn2KMxwSd3vu+ifsS1WWGlJHNQ1vKmV5WvFyDInxRlmueDZsBNJLis274R3c38DQxqi6+yVwYGA2jwFFPvOheJNi/o60b98lPLzFrUGL+9zupth0HzYCnoYdtgow6Wh76/AFdrpWgM2GB+I6CXyabfcTO3KjNV8EZXnwC/EmrEaWwpbm5af+PL04Uoy4FtKqPFujRv3oyBKGmbuYzjK4=
